#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Run Prettier to check for formatting issues
npx prettier --write .

# Run ESLint to check for linting issues
npx eslint .

# If any issues are found, display an error message and exit
if [ $? -ne 0 ]; then
  echo "Please fix the linting and formatting issues before committing."
  exit 1
fi